### ISSUE TITLE
Missing tornado in pip dependencies

### ISSUE THREAD

**Issue by llann** [fiduswriter/django-npm-mjs#2]
Tornado dependency not installed when `pip install django-npm-mjs`

**Comment by johanneswilm** [comment]
I see. We probably should not use the entire tornado package as we are only using json_decode here. It's probably better to use an equivalent function from https://docs.python.org/3/library/json.html . It needs to be Python2/3 compatible though.

**Comment by johanneswilm** [comment]
fixed in 0.7.0
